server:
  port: 9999

#spring:
#  application:
#    name: member
#  config:
#    import: configserver:http://localhost:8888
#  cloud:
#    config:
#      uri: http://localhost:8888
#      profile: local
#      label: main

management:
  endpoints:
    web:
      exposure:
        include: refresh